[package]
name = "flockfile"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
thiserror = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.24"
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
assert_matches = "1.5"
tempfile = "3.2"
