[package]
name = "logged_command"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
log = "0.4"
nix = "0.26"
tokio = { version = "1.23", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "rt",
] }

[dev-dependencies]
anyhow = "1.0"
tedge_test_utils = { path = "../../tests/tedge_test_utils" }
