[package]
name = "tedge_timer_ext"
description = "thin-edge extension adding timers"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1"
tedge_actors = { path = "../../core/tedge_actors" }
tokio = { version = "1.23", default_features = false, features = ["time"] }
