[package]
name = "json-writer"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
serde_json = "1"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
