[package]
name = "download"
description = "download_manager"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
backoff = { version = "0.4", features = ["tokio"] }
log = "0.4"
nix = "0.24"
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls-native-roots",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_utils = { path = "../tedge_utils" }
thiserror = "1.0"
tokio = { version = "1.23", features = ["fs"] }
url = "2.2"

[dev-dependencies]
mockito = "0.31"
regex = "1.5"
tempfile = "3.2"
test-case = "2.2"
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
